version: '3'
services:
  #||---------------------------------||
  #|| CONTAINER FOR lucasratiaray.fr  ||
  #||---------------------------------||
  # lucasratiaray-portfolio:
  #   container_name: portfolio_lucasratiaray
  #   image: node:lts-alpine
  #   working_dir: /app
  #   expose:
  #     - "8000"
  #   environment:
  #     - HOST=lucasratiaray-portfolio
  #     - PORT=8000
  #   command: sh -c "npm install && npm run build && node ./dist/server/entry.mjs"
  #   volumes:
  #     - ./www/lucasratiaray.fr:/app
  #   networks:
  #     - backend

  #||-----------------------------------||
  #|| EXAMPLE OF PHP-APACHE CONTAINER   ||
  #||-----------------------------------||
  php-apache:
    container_name: php_apache
    build: site
    expose:
      - "8000"
    volumes:
      - ./maintenance:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini
      - ./server/ports.conf:/etc/apache2/ports.conf
    networks:
      - backend

  #||-----------------------------------||
  #|| CONTAINER FOR rebellab.tech       ||
  #||-----------------------------------||
  php-apache-rebellab:
    container_name: php_apache_rebellab
    build: site
    expose:
      - "8001"
    volumes:
    # - ./www/rebellab.tech:/var/www/html/ # For production
      - ./maintenance:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini
      - ./server/ports.conf:/etc/apache2/ports.conf
    networks:
      - backend

  #||-----------------------------------||
  #|| CONTAINER FOR NGINX REVERSE PROXY ||
  #||-----------------------------------||
  nginx:
    container_name: nginx_reverse_proxy
    restart: unless-stopped
    image: nginx
    ports:
        - "80:80"
        - "443:443"
    depends_on:
      # - lucasratiaray-portfolio # For production on lucasratiaray-portfolio
      - php-apache
      - php-apache-rebellab
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
    networks:
      - backend

  #||-----------------------------------||
  #|| CONTAINER FOR CERTBOT             ||
  #||-----------------------------------||
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email contact.ratiaray@gmail.com -d lucasratiaray.fr -d rebellab.tech --agree-tos
    networks:
      - backend

networks:
  backend: